name: lint
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: stable
        check-latest: true
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Lint
      run: make lint/ci
