name: reviewdog
on:
  pull_request:
jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.x
    - name: golangci-lint
      uses: reviewdog/action-golangci-lint@v2
      with:
        reviewdog_flags: '-conf=.reviewdog.yml -diff="git diff main"'
        golangci_lint_version: v1.52.2
    - name: looppointer
      run: make lint/looppointer
