name: reviewdog
on:
  pull_request:
jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        # TODO
        # go-version: 1.20.x
        go-version: 1.19.x
    - name: golangci-lint
      uses: reviewdog/action-golangci-lint@v2
      with:
        golangci_lint_version: v1.48.0
        fail_on_error: true
    - name: looppointer
      run: make lint/looppointer
