name: run-examples
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go-version: [stable, oldstable]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
        check-latest: true
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build
      run: make build
    - name: Run examples
      run: make test/examples
