name: test on tip
on:
  schedule:
  - cron: '3 * * * *'
  pull_request:
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.x
    - name: Install Go tip
      run: |
        go install golang.org/dl/gotip@latest
        gotip download
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Generate codes and plugins
      env:
        GO: gotip
      run: make gen
    - name: Test
      env:
        GO: gotip
      run: make test/norace
